definitions:
  app.CommentsResponse:
    properties:
      author:
        type: string
      created_at:
        type: string
      text:
        type: string
    type: object
  app.CreateCommentRequest:
    properties:
      author:
        type: string
      resource:
        type: string
      site:
        type: string
      text:
        type: string
    type: object
  http.JwtResponse:
    properties:
      token:
        type: string
    type: object
  http.loginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  infrastructure.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/{site}/{resource}/comments:
    get:
      description: get comments for site and resource
      parameters:
      - description: Site identifier
        in: path
        name: site
        required: true
        type: string
      - description: Resource identifier
        in: path
        name: resource
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/app.CommentsResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infrastructure.ErrorResponse'
      summary: Get comments
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: Create comment for site and resource
      parameters:
      - description: Site identifier
        in: path
        name: site
        required: true
        type: string
      - description: Resource identifier
        in: path
        name: resource
        required: true
        type: string
      - description: Comment to create
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/app.CreateCommentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.CommentsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infrastructure.ErrorResponse'
      summary: Create comment
      tags:
      - comments
  /api/admin/{site}:
    post:
      consumes:
      - application/json
      description: Create site
      parameters:
      - description: Site identifier
        in: path
        name: site
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infrastructure.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/infrastructure.ErrorResponse'
      summary: Create site
      tags:
      - comments
  /oauth/token:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Generate JWT token for valid user credentials
      parameters:
      - description: login
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      - description: Login credentials
        in: body
        name: request
        schema:
          $ref: '#/definitions/http.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.JwtResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infrastructure.ErrorResponse'
      summary: Generate JWT token
      tags:
      - auth
swagger: "2.0"
